version: "2.1"
services:
  dev:
    image: js_expert_06
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/js_expert_06
      - node_modules:/js_expert_06/node_modules
    ports:
      - 3000:3000
       
  test:
    image: js_expert_06
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      - .:/js_expert_06
      - node_modules:/js_expert_06/node_modules

  test-watch:
    image: js_expert_06
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/js_expert_06
      - node_modules:/js_expert_06/node_modules
  
  test-coverage:
    image: js_expert_06
    build: .
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/js_expert_06
      - node_modules:/js_expert_06/node_modules
volumes:
  node_modules: {}