version: "2.1"
services:
  dev:
    image: js_expert_06
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/js_expert_06
      - node_modules:/js_expert_06/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: {}